### ISSUE TITLE
Using macro mod inChat button crashes the game

### ISSUE THREAD

**Issue by Brottweiler** [killjoy1221/tabbychat#12]
In `inChat` I have a button that runs `/staff`, when I press it, I crash:

```
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at acs.tabbychat.core.TabbyChat.processChat(TabbyChat.java:681)
	at acs.tabbychat.core.GuiNewChatTC.func_146237_a(GuiNewChatTC.java:390)
	at acs.tabbychat.core.GuiNewChatTC.a(GuiNewChatTC.java:549)
	at acs.tabbychat.core.GuiNewChatTC.a(GuiNewChatTC.java:544)
	at bjb.a(SourceFile:474)
	at gj.a(SourceFile:38)
	at gj.a(SourceFile:9)
	at ej.a(SourceFile:174)
	at bje.e(SourceFile:212)
	at bao.p(SourceFile:1306)
	at bao.ak(SourceFile:774)
	at bao.f(SourceFile:728)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by killjoy1221** [comment]
Try it now.

**Comment by Brottweiler** [comment]
Seems to work!
